### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_points_kernels.points_cpu

### ISSUE THREAD

**Issue by mackenziebeggs** [nicolas-chaulet/torch-points-kernels#66]
Hi Nicolas,
Thank you so much for all of the great work you are doing on this repository, it is greatly appreciated.
Unfortunately, I am experiencing an installation issue, and I was hoping you could please provide some insight. I am working with Docker.

With the latest PyTorch 1.8.0 update, my working version of everything broke.
Here is an excerpt of the previously functioning environment:
```Dockerfile
ARG VERSION=1.7.0
ARG CUDA="102"
pip3 install --no-cache-dir
        torch-scatter torch-sparse torch-cluster torch-spline-conv \
        -f https://pytorch-geometric.com/whl/torch-${VERSION}+${CUDA}.html &&\
        pip3 install --no-cache-dir \
        torch-geometric torch-points-kernels==0.6.1
```

I have been able to successfully build torch-scatter, torch-sparse, torch-cluster, torch-spline-conv, and  torch-geometric within the container by upgrading to PyTorch 1.8.0.  The current issue comes when installing torch-points-kernels.

I am using an [official pytorch image](https://hub.docker.com/r/pytorch/pytorch/tags?page=1&ordering=last_updated ), which can be obtained via: docker pull pytorch/pytorch:1.8.0-cuda11.1-cudnn8-devel

Here is a minimally reproducible example:
```Dockerfile
FROM pytorch/pytorch:1.8.0-cuda11.1-cudnn8-devel
RUN pip3 install --no-cache-dir \
        torch-points-kernels==0.6.1
ENTRYPOINT ["python3"]
```

Here is the Traceback:

```python
import torch_points_kernels
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/torch_points_kernels/__init__.py", line 1, in <module>
    from .torchpoints import *
  File "/opt/conda/lib/python3.8/site-packages/torch_points_kernels/torchpoints.py", line 7, in <module>
    import torch_points_kernels.points_cpu as tpcpu
ModuleNotFoundError: No module named 'torch_points_kernels.points_cpu'
```

The environment has: 
- Python 3.8.8
- GCC 7.3.0

Following your troubleshooting guide:
```bash
$ python -c "import torch; print(torch.__version__)"
>>> 1.8.0
```

```bash
$ echo $PATH
>>> /opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

```bash
$ echo $CPATH
>>> /usr/local/cuda/include
```

Here is the output of the unnittest, building inside the container via:
```bash
$ python setup.py build_ext --inplace
$ python -m unittest
```

```bash
Ran 32 tests in 32.106s
OK
```
I can then successfully import torch-points-kernels, so it appears installing from source works. Unfortunately, this is extremely time consuming (~ 300 seconds); I notice that for any version > 1.6.1 this is the case. Hope this information is useful.

Best,
Mackenzie

**Comment by nicolas-chaulet** [comment]
Hi! Thanks for the update, I actually don't think that we have ever supported pre-built packages but thanks for the info!

**Comment by ThorJonsson** [comment]
Is it possible to keep this issue open until this codebase has been updated so you don't have to install from source with pytorch 1.8?

**Comment by nicolas-chaulet** [comment]
Hey @ThorJonsson I can reopen that, it just seems that you are using a rather old verion, maybe that's the problem? Can you try to update to 0.6.10?

**Comment by nicolas-chaulet** [comment]
Hi, as suggested, could you try to use the latest release of torch-points-kernel? It is 0.6.10 not 0.6.1.

**Comment by TangToy** [comment]
I also encountered this problem.  I cloned the code on https://github.com/torch-points3d/torch-points-kernels, and build the code :
```
python setup.py build_ext --inplace
python -m unittest
```
as the README.md says.

After buiding, I move the folder torch_points_kernels to my project, and the problem solved.

**Comment by douwenhao68** [comment]
".point-cpu" cannot be imported due to the error file "point-cpu.so"  built by  pip-install , TangToy is right

**Comment by CCInc** [comment]
Closing for now, feel free to reopen if still an issue.
